/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TimesheetsCreateIndexRouteImport } from './routes/timesheets/create/index'
import { Route as TimesheetsEntryDateIndexRouteImport } from './routes/timesheets/$entryDate/index'
import { Route as TimesheetsEntryDateTimesheetIdIndexRouteImport } from './routes/timesheets/$entryDate/$timesheetId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimesheetsCreateIndexRoute = TimesheetsCreateIndexRouteImport.update({
  id: '/timesheets/create/',
  path: '/timesheets/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimesheetsEntryDateIndexRoute =
  TimesheetsEntryDateIndexRouteImport.update({
    id: '/timesheets/$entryDate/',
    path: '/timesheets/$entryDate/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TimesheetsEntryDateTimesheetIdIndexRoute =
  TimesheetsEntryDateTimesheetIdIndexRouteImport.update({
    id: '/timesheets/$entryDate/$timesheetId/',
    path: '/timesheets/$entryDate/$timesheetId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/timesheets/$entryDate': typeof TimesheetsEntryDateIndexRoute
  '/timesheets/create': typeof TimesheetsCreateIndexRoute
  '/timesheets/$entryDate/$timesheetId': typeof TimesheetsEntryDateTimesheetIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/timesheets/$entryDate': typeof TimesheetsEntryDateIndexRoute
  '/timesheets/create': typeof TimesheetsCreateIndexRoute
  '/timesheets/$entryDate/$timesheetId': typeof TimesheetsEntryDateTimesheetIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/timesheets/$entryDate/': typeof TimesheetsEntryDateIndexRoute
  '/timesheets/create/': typeof TimesheetsCreateIndexRoute
  '/timesheets/$entryDate/$timesheetId/': typeof TimesheetsEntryDateTimesheetIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/timesheets/$entryDate'
    | '/timesheets/create'
    | '/timesheets/$entryDate/$timesheetId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/timesheets/$entryDate'
    | '/timesheets/create'
    | '/timesheets/$entryDate/$timesheetId'
  id:
    | '__root__'
    | '/'
    | '/timesheets/$entryDate/'
    | '/timesheets/create/'
    | '/timesheets/$entryDate/$timesheetId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TimesheetsEntryDateIndexRoute: typeof TimesheetsEntryDateIndexRoute
  TimesheetsCreateIndexRoute: typeof TimesheetsCreateIndexRoute
  TimesheetsEntryDateTimesheetIdIndexRoute: typeof TimesheetsEntryDateTimesheetIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timesheets/create/': {
      id: '/timesheets/create/'
      path: '/timesheets/create'
      fullPath: '/timesheets/create'
      preLoaderRoute: typeof TimesheetsCreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timesheets/$entryDate/': {
      id: '/timesheets/$entryDate/'
      path: '/timesheets/$entryDate'
      fullPath: '/timesheets/$entryDate'
      preLoaderRoute: typeof TimesheetsEntryDateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timesheets/$entryDate/$timesheetId/': {
      id: '/timesheets/$entryDate/$timesheetId/'
      path: '/timesheets/$entryDate/$timesheetId'
      fullPath: '/timesheets/$entryDate/$timesheetId'
      preLoaderRoute: typeof TimesheetsEntryDateTimesheetIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TimesheetsEntryDateIndexRoute: TimesheetsEntryDateIndexRoute,
  TimesheetsCreateIndexRoute: TimesheetsCreateIndexRoute,
  TimesheetsEntryDateTimesheetIdIndexRoute:
    TimesheetsEntryDateTimesheetIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
