/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntryDateIndexRouteImport } from './routes/$entryDate/index'
import { Route as EntryDateCreateIndexRouteImport } from './routes/$entryDate/create/index'
import { Route as EntryDateTimesheetIdIndexRouteImport } from './routes/$entryDate/$timesheetId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryDateIndexRoute = EntryDateIndexRouteImport.update({
  id: '/$entryDate/',
  path: '/$entryDate/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryDateCreateIndexRoute = EntryDateCreateIndexRouteImport.update({
  id: '/$entryDate/create/',
  path: '/$entryDate/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryDateTimesheetIdIndexRoute =
  EntryDateTimesheetIdIndexRouteImport.update({
    id: '/$entryDate/$timesheetId/',
    path: '/$entryDate/$timesheetId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$entryDate': typeof EntryDateIndexRoute
  '/$entryDate/$timesheetId': typeof EntryDateTimesheetIdIndexRoute
  '/$entryDate/create': typeof EntryDateCreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$entryDate': typeof EntryDateIndexRoute
  '/$entryDate/$timesheetId': typeof EntryDateTimesheetIdIndexRoute
  '/$entryDate/create': typeof EntryDateCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$entryDate/': typeof EntryDateIndexRoute
  '/$entryDate/$timesheetId/': typeof EntryDateTimesheetIdIndexRoute
  '/$entryDate/create/': typeof EntryDateCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$entryDate'
    | '/$entryDate/$timesheetId'
    | '/$entryDate/create'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$entryDate' | '/$entryDate/$timesheetId' | '/$entryDate/create'
  id:
    | '__root__'
    | '/'
    | '/$entryDate/'
    | '/$entryDate/$timesheetId/'
    | '/$entryDate/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntryDateIndexRoute: typeof EntryDateIndexRoute
  EntryDateTimesheetIdIndexRoute: typeof EntryDateTimesheetIdIndexRoute
  EntryDateCreateIndexRoute: typeof EntryDateCreateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$entryDate/': {
      id: '/$entryDate/'
      path: '/$entryDate'
      fullPath: '/$entryDate'
      preLoaderRoute: typeof EntryDateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$entryDate/create/': {
      id: '/$entryDate/create/'
      path: '/$entryDate/create'
      fullPath: '/$entryDate/create'
      preLoaderRoute: typeof EntryDateCreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$entryDate/$timesheetId/': {
      id: '/$entryDate/$timesheetId/'
      path: '/$entryDate/$timesheetId'
      fullPath: '/$entryDate/$timesheetId'
      preLoaderRoute: typeof EntryDateTimesheetIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntryDateIndexRoute: EntryDateIndexRoute,
  EntryDateTimesheetIdIndexRoute: EntryDateTimesheetIdIndexRoute,
  EntryDateCreateIndexRoute: EntryDateCreateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
